module Everything where

import BasicSystem.Utils
import BasicSystem.BigStepSemantics
import BasicSystem.OPE 
import BasicSystem.RecursiveNormaliser
import BasicSystem.StructuralNormaliser 
import BasicSystem.Conversion
import BasicSystem.OPEBigStep
import BasicSystem.Soundness
import BasicSystem.Syntax
import BasicSystem.Embeddings
import BasicSystem.OPELemmas
import BasicSystem.StrongComputability
import BasicSystem.TerminationandCompleteness
import BasicSystem.IdentityEnvironment
import BasicSystem.OPERecursive
import BasicSystem.StrongConvertibility

import FiniteProducts.Utils
import FiniteProducts.BigStepSemantics
import FiniteProducts.OPE 
import FiniteProducts.RecursiveNormaliser
import FiniteProducts.StructuralNormaliser 
import FiniteProducts.Conversion
import FiniteProducts.OPEBigStep
import FiniteProducts.Soundness
import FiniteProducts.Syntax
import FiniteProducts.Embeddings
import FiniteProducts.OPELemmas
import FiniteProducts.StrongComputability
import FiniteProducts.TerminationandCompleteness
import FiniteProducts.IdentityEnvironment
import FiniteProducts.OPERecursive
import FiniteProducts.StrongConvertibility

import NaturalNumbers.Utils
import NaturalNumbers.BigStepSemantics
import NaturalNumbers.OPE 
import NaturalNumbers.RecursiveNormaliser
import NaturalNumbers.StructuralNormaliser 
import NaturalNumbers.Conversion
import NaturalNumbers.OPEBigStep
import NaturalNumbers.Soundness
import NaturalNumbers.Syntax
import NaturalNumbers.Embeddings
import NaturalNumbers.OPELemmas
import NaturalNumbers.StrongComputability
import NaturalNumbers.TerminationandCompleteness
import NaturalNumbers.IdentityEnvironment
import NaturalNumbers.OPERecursive
import NaturalNumbers.StrongConvertibility

import FullSystem.Utils
